spring:
  datasource:
    url: jdbc:h2:mem:travelagency
    username: sa
    password: ${DATABASE_PSW}
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  jackson:
    default-property-inclusion: non_empty
  main:
    allow-circular-references: true
