spring:
  datasource:
    url: jdbc:h2:mem:travelagency
    username: sa
    password: ${DATABASE_PSW}
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  jms:
    servicebus:
      connection-string: ${SB_CS}
      idle-timeout: 1800000
      pricing-tier: premium
  jackson:
    default-property-inclusion: non_null
  main:
    allow-circular-references: true
